services:
  fastapi:
    container_name: fastapi_backend
    restart: unless-stopped
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
        - action: rebuild
          path: ./backend/pyproject.toml
    # network_mode: host
    networks:
      - dev-network
  n8n:
    container_name: n8n_server
    restart: unless-stopped
    build:
      context: ./n8n
      dockerfile: Dockerfile
      # args:
      #   N8N_VERSION: 2.9.1
    environment:
      - GENERIC_TIMEZONE=Europe/Budapest
      - TZ=Europe/Budapest
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - ./n8n/n8n_data:/home/node/.n8n
      - ./agent_node/dist:/home/node/.n8n/custom:ro  # for development
    ports:
      - "5678:5678"
    develop:
      watch:
        - action: sync
          path: ./n8n/n8n_data
          target: /home/node/.n8n
    # network_mode: host
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
